name: Manual Deployment Trigger

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
          - prod
      component:
        description: 'Component to deploy'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - backend
          - frontend
      image_tag:
        description: 'Image tag to deploy (leave empty for latest)'
        required: false
        type: string

env:
  REGISTRY: docker.io
  BACKEND_IMAGE_NAME: akpadetsi/event-booking-backend
  FRONTEND_IMAGE_NAME: akpadetsi/event-booking-frontend

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - name: Checkout manifests repository
        uses: actions/checkout@v4
        with:
          repository: cloudenochcsis/gitops-k8s-manifests
          token: ${{ secrets.GITOPS_TOKEN }}
          path: manifests

      - name: Set up git config
        run: |
          cd manifests
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Determine image tag
        id: tag
        run: |
          if [ -n "${{ inputs.image_tag }}" ]; then
            echo "IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_OUTPUT
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Update backend image tag
        if: inputs.component == 'all' || inputs.component == 'backend'
        run: |
          cd manifests
          sed -i "s|akpadetsi/event-booking-backend:.*|akpadetsi/event-booking-backend:${{ steps.tag.outputs.IMAGE_TAG }}|g" backend-complete.yaml
          echo "Updated backend image to: akpadetsi/event-booking-backend:${{ steps.tag.outputs.IMAGE_TAG }}"

      - name: Update frontend image tag
        if: inputs.component == 'all' || inputs.component == 'frontend'
        run: |
          cd manifests
          sed -i "s|akpadetsi/event-booking-frontend:.*|akpadetsi/event-booking-frontend:${{ steps.tag.outputs.IMAGE_TAG }}|g" frontend-complete.yaml
          echo "Updated frontend image to: akpadetsi/event-booking-frontend:${{ steps.tag.outputs.IMAGE_TAG }}"

      - name: Commit and push changes
        run: |
          cd manifests
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "Manual deployment to ${{ inputs.environment }}: ${{ inputs.component }} with tag ${{ steps.tag.outputs.IMAGE_TAG }}"
            git push
            echo "Pushed updated manifests for ${{ inputs.environment }} environment"
          fi

      - name: Deployment summary
        run: |
          echo "## Manual Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **Environment**: ${{ inputs.environment }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Component**: ${{ inputs.component }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image Tag**: ${{ steps.tag.outputs.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Status**: Manifests updated successfully" >> $GITHUB_STEP_SUMMARY
          echo "- **Next**: ArgoCD will automatically sync the changes" >> $GITHUB_STEP_SUMMARY
